group: edge
language: java
jdk: oraclejdk8
install: true
script:
  # testing main version
  - bash gradlew clean assemble --stacktrace
  - bash gradlew check license build --stacktrace
  - bash gradlew install publish --stacktrace
  # testing other gradle versions:
  - >
    for version in 4.0 4.0.1 4.0.2; do
      gradle wrapper --gradle-version $version;
      bash gradlew -v;
      bash gradlew clean check license build install publish --stacktrace;
      bash gradlew --stop;
      rm -rf $HOME/.gradle
    done;
before_cache:
  - bash gradlew --stop
  - rm -rf $HOME/.m2/repository/io/github/daggerok
  - rm -rf $HOME/.gradle/caches/modules-2/files-2.1/gradle.plugin*
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
