group: edge
language: java
jdk: oraclejdk8
install: true
script:
  - bash gradlew clean assemble --stacktrace
  - bash gradlew check license build --stacktrace
  - bash gradlew install publish --stacktrace
before_cache:
  - gradle --stop
  - rm -rf $HOME/.m2/repository/io/github/daggerok
  - rm -rf $HOME/.gradle/caches/modules-2/files-2.1/gradle.plugin*
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
