group: edge
language: java
jdk: oraclejdk8
install: true
before_install:
  # sdkman installation
  - curl -s "https://get.sdkman.io" | bash
  - mkdir -p "$HOME/.sdkman/etc"
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
script:
  # testing main used version
  - bash gradlew clean assemble --stacktrace
  - bash gradlew check license build --stacktrace
  - bash gradlew install publish --stacktrace
  # testing other gradle versions: 3.0, 3.1, 3.2, 3.2.1, 3.3, 3.4, 3.4.1, 3.5, 3.5.1, 4.0, 4.0.1, 4.1-rc-1
  - for version in 3.0 3.5 4.0; do sdk use gradle "version$i"; source "$HOME/.sdkman/bin/sdkman-init.sh"; gradle clean assemble check license build install publish --stacktrace; done;
before_cache:
  - bash gradlew --stop
  - rm -rf $HOME/.m2/repository/io/github/daggerok
  - rm -rf $HOME/.gradle/caches/modules-2/files-2.1/gradle.plugin*
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
